services:
  db-clima:
    image: postgres:15
    container_name: db_clima
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 73
      POSTGRES_DB: db-clima
    ports:
      - "5440:5432"
    volumes:
      - data-clima:/var/lib/postgresql/data
  
  clima-api:
    build:
      context: ./clima-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db-clima:5432/db-clima
      - DB_USERNAME=dev
      - DB_PASSWORD=73
  frontend:
    build:
      context: ./frontend
    container_name: frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://clima-api:8000
    depends_on:
      - clima-api
volumes:
  data-clima: {}

